# image will be published to ghcr.io/<user>/<name>
name: fedora-atomic-awesome
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      - https://pkgs.tailscale.com/unstable/fedora/tailscale.repo
      - https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    install:
      - awesome
      - clojure
      - kitty
      - rofi
      - emacs
      - flameshot
      - fzf
      - direnv
      - dunst
      - flatpak-builder
      - mplayer
      - nethogs
      - packer
      - pnpm
      - podman-compose
      - polybar
      - subl
      - tailscale
      - tldr
      - zoxide
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.bitwarden.desktop
        - com.calibre_ebook.calibre
        - com.github.finefindus.eyedropper
        - com.github.tenderowl.frog
        - com.google.Chrome
        - com.logseq.Logseq
        - com.spotify.Client
        - com.todoist.Todoist
        - com.usebruno.Bruno
        - io.github.nate_xyz.Conjure
        - io.podman_desktop.PodmanDesktop
        - life.bolls.bolls
        - org.mozilla.firefox
        - org.zealdocs.Zeal
        - fi.skyjake.Lagrange
        - com.slack.Slack
        - com.valvesoftware.Steam

        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

